# CMake generated Testfile for 
# Source directory: /homea/ias-5/wenping/software/gromacs-5.1.2_EtMg/src/gromacs
# Build directory: /homea/ias-5/wenping/software/gromacs-5.1.2_EtMg/build_frontend_jureca/src/gromacs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gmxlib")
subdirs("mdlib")
subdirs("listed-forces")
subdirs("commandline")
subdirs("domdec")
subdirs("ewald")
subdirs("fft")
subdirs("linearalgebra")
subdirs("math")
subdirs("mdrunutility")
subdirs("random")
subdirs("onlinehelp")
subdirs("options")
subdirs("pbcutil")
subdirs("timing")
subdirs("topology")
subdirs("utility")
subdirs("fileio")
subdirs("swap")
subdirs("essentialdynamics")
subdirs("pulling")
subdirs("simd")
subdirs("imd")
subdirs("legacyheaders")
subdirs("gmxana")
subdirs("gmxpreprocess")
subdirs("correlationfunctions")
subdirs("statistics")
subdirs("analysisdata")
subdirs("selection")
subdirs("trajectoryanalysis")
subdirs("tools")
