# CMake generated Testfile for 
# Source directory: /home/wenping/software/gromacs-5.1.2_EtMg/tests
# Build directory: /home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(regressiontests/simple "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "simple" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/simple PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
add_test(regressiontests/complex "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "complex" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/complex PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
add_test(regressiontests/kernel "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "kernel" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/kernel PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
add_test(regressiontests/freeenergy "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "freeenergy" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/freeenergy PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
add_test(regressiontests/pdb2gmx "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "pdb2gmx" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/pdb2gmx PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
add_test(regressiontests/rotation "perl" "/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/tests/regressiontests-5.1.2/gmxtest.pl" "rotation" "-crosscompile" "-noverbose" "-nosuffix")
set_tests_properties(regressiontests/rotation PROPERTIES  ENVIRONMENT "PATH=/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/lib:/home/wenping/software/gromacs-5.1.2_EtMg/build_frontend_gpuws/bin:/home/wenping/bin:/home/wenping/.local/bin:/usr/local/gromacs-2016.3/bin:/usr/local/cuda-8.0/bin:/home/wenping/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wenping/nanocal_div/bin:/home/wenping/nanocall_diy1/bin")
